name: build-test-tidy-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  require-label:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/require-label.yaml@v1
    with:
      label: run:build-and-test-differential

  build-and-test-differential:
    if: ${{ always() }}
    needs:
      - require-label
    uses: ./.github/workflows/build-and-test-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:core-devel
      run-condition: ${{ needs.require-label.outputs.result == 'true' }}
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  clang-tidy-differential:
    if: ${{ always() }} # always run to provide report for status check
    needs:
      - build-and-test-differential
    uses: ./.github/workflows/clang-tidy-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:core-devel
      run-condition: true
